### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by mitiandi** [MIC-DKFZ/medicaldetectiontoolkit#29]
Hi,
    There are something wrong that confused me when I re-compiled the cuda fuctions. 
`(venv) xliu@310-aa:~/medicaldetectiontoolkit/cuda_functions/nms_2D$ python build       .py
Including CUDA code.
/home/xliu/medicaldetectiontoolkit/cuda_functions/nms_2D
generating /tmp/tmpaxsbcnrt/_nms.c
setting the current directory to '/tmp/tmpaxsbcnrt'
running build_ext
building '_nms' extension
creating home
creating home/xliu
creating home/xliu/medicaldetectiontoolkit
creating home/xliu/medicaldetectiontoolkit/cuda_functions
creating home/xliu/medicaldetectiontoolkit/cuda_functions/nms_2D
creating home/xliu/medicaldetectiontoolkit/cuda_functions/nms_2D/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes        -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORT       IFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/xliu/medicaldetectiontoolkit/venv/lib/pyt       hon3.5/site-packages/torch/utils/ffi/../../lib/include -I/home/xliu/medicaldetec       tiontoolkit/venv/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/T       H -I/home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site-packages/torch/ut       ils/ffi/../../lib/include/THC -I/usr/include/python3.5m -I/home/xliu/medicaldete       ctiontoolkit/venv/include/python3.5m -c _nms.c -o ./_nms.o -std=c99
In file included from /home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site       -packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _nms.c:493:
**/home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site-packages/torch/utils/       ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file        or directory
compilation terminated.**
Traceback (most recent call last):
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
**distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with        exit status 1**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site-packages/cffi       /ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_e       xtensions
    self._build_extensions_serial()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_       extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_e       xtension
    depends=ext.depends)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
**distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site-packages/torc       h/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site-packages/torc       h/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site-packages/cffi       /api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site-packages/cffi       /recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site-packages/cffi       /ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/xliu/medicaldetectiontoolkit/venv/lib/python3.5/site-packages/cffi       /ffiplatform.py", line 58, in _build
    **raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1**
`

**Comment by pfjaeger** [comment]
hi what cuda version do you have installed?

**Comment by mitiandi** [comment]
> hi what cuda version do you have installed?

Thank you! I have solved this problem with adding the path of cuda.h in nvcc's include path.

**Comment by arthur801031** [comment]
Hi @mitiandi 

What's the exact command that you used to get it to work?

I've tried
```
nvcc -c -o nms_kernel.cu.o nms_kernel.cu -include /workspace/usr/local/cuda-9.0/include/cuda.h -x cu -Xcompiler -fPIC -arch=sm_61
```

and 

```
nvcc -c -o nms_kernel.cu.o nms_kernel.cu -I /workspace/usr/local/cuda-9.0/include -x cu -Xcompiler -fPIC -arch=sm_61
```

But none of them worked. 
Please help. 

Thank you so much.
