### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by wgs123** [MIC-DKFZ/medicaldetectiontoolkit#30]
I running the preprocessing.py and meet an error
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\medicaldetectiontoolkit-master\experiments\lidc_exp\preprocessing.py", line 56, in pp_patient
    img_arr = resample_array(img_arr, img.GetSpacing(), cf.target_spacing)
  File "C:\medicaldetectiontoolkit-master\experiments\lidc_exp\preprocessing.py", line 44, in resample_array
    resampled_img = tf.resize(img, target_shape, order=1, clip=True, mode='edge')
  File "C:\ProgramData\Anaconda3\lib\site-packages\skimage\transform\_warps.py", line 177, in resize
    indexing='ij'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py", line 4060, in meshgrid
    output = [x.copy() for x in output]
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py", line 4060, in <listcomp>
    output = [x.copy() for x in output]
MemoryError
"""

**Comment by pfjaeger** [comment]
if your cpu memory is too small you should turn down the number of processes, did you try that?
