### ISSUE TITLE
raise ValueError("MirrorTransform now takes the axes as the spatial dimensions. What previously was " ValueError: MirrorTransform now takes the axes as the spatial dimensions. What previously was axes=(2, 3, 4) to mirror along all spatial dimensions of a 5d tensor (b, c, x, y, z) is now axes=(0, 1, 2). Please adapt your scripts accordingly.

### ISSUE THREAD

**Issue by wgs123** [MIC-DKFZ/medicaldetectiontoolkit#31]
Traceback (most recent call last):
  File "/home/wgs/medicaldetectiontoolkit/exec.py", line 167, in <module>
    train(logger)
  File "/home/wgs/medicaldetectiontoolkit/exec.py", line 53, in train
    batch_gen = data_loader.get_train_generators(cf, logger)
  File "experiments/lidc_exp/data_loader.py", line 76, in get_train_generators
    batch_gen['train'] = create_data_gen_pipeline(train_data, cf=cf, is_training=True)
  File "experiments/lidc_exp/data_loader.py", line 181, in create_data_gen_pipeline
    mirror_transform = Mirror(axes=np.arange(2, cf.dim+2, 1))
  File "/home/wgs/batchgenerators/batchgenerators/transforms/spatial_transforms.py", line 192, in __init__
    raise ValueError("MirrorTransform now takes the axes as the spatial dimensions. What previously was "
ValueError: MirrorTransform now takes the axes as the spatial dimensions. What previously was axes=(2, 3, 4) to mirror along all spatial dimensions of a 5d tensor (b, c, x, y, z) is now axes=(0, 1, 2). Please adapt your scripts accordingly.

**Comment by pfjaeger** [comment]
thanks for the hint. line 181 the lidc data loader should now read:
`mirror_transform = Mirror(axes=np.arange(cf.dim))`

I will commit this change
