### ISSUE TITLE
mrcnn.py error

### ISSUE THREAD

**Issue by wgs123** [MIC-DKFZ/medicaldetectiontoolkit#34]
Traceback (most recent call last):
  File "/home/wgs/medicaldetectiontoolkit/exec.py", line 167, in <module>
    train(logger)
  File "/home/wgs/medicaldetectiontoolkit/exec.py", line 69, in train
    results_dict = net.train_forward(batch)
  File "models/mrcnn.py", line 873, in train_forward
    rpn_class_logits, rpn_pred_deltas, proposal_boxes, detections, detection_masks = self.forward(img)
  File "models/mrcnn.py", line 990, in forward
    fpn_outs = self.fpn(img)
  File "/home/wgs/medicaldetectiontoolkit/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "models/backbone.py", line 153, in forward
    p2_pre_out = self.P2_conv1(c2_out) + F.interpolate(p3_pre_out, scale_factor=2)
RuntimeError: The size of tensor a (39) must match the size of tensor b (40) at non-singleton dimension 3

**Comment by pfjaeger** [comment]
your input shape needs to be divisible by 2**n, where n is the number of pooling operations in your network. Please adjust your input shape accordingly. i will add a  warning to catch this mistake.
