### ISSUE TITLE
Error During Transferring Pre-trained RetinaNet LIDC Model

### ISSUE THREAD

**Issue by ivanwilliammd** [MIC-DKFZ/medicaldetectiontoolkit#43]
Hello Sir Paul, thank you for the suggestion you give me
I have tried to transfer the LIDC pre-trained weight, however I face several issue:

```
Traceback (most recent call last):
  File "exec.py", line 167, in <module>
    train(logger)
  File "exec.py", line 46, in train
    starting_epoch = utils.load_checkpoint(cf.resume_to_checkpoint, net, optimizer)
  File "/home/ivan/retcustom3d/utils/exp_utils.py", line 186, in load_checkpoint
    net.load_state_dict(checkpoint['state_dict'])
  File "/home/ivan/.virtualenvs/virtual-py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for net:
        Missing key(s) in state_dict: "Fpn.C1.0.weight", "Fpn.C1.0.bias", "Fpn.C2.1.conv1.0.weight", "Fpn.C2.1.conv1.0.bias", "Fpn.C2.1.conv2.0.weight", "Fpn.C2.1.conv2.0.bias", "Fpn.C2.1.conv3.weight", "Fpn.C2.1.conv3.bias", "Fpn.C2.1.downsample.weight", "Fpn.C2.1.downsample.bias", "Fpn.C2.2.conv1.0.weight", "Fpn.C2.2.conv1.0.bias", "Fpn.C2.2.conv2.0.weight", "Fpn.C2.2.conv2.0.bias", "Fpn.C2.2.conv3.weight", "Fpn.C2.2.conv3.bias", "Fpn.C2.3.conv1.0.weight", "Fpn.C2.3.conv1.0.bias", "Fpn.C2.3.conv2.0.weight", "Fpn.C2.3.conv2.0.bias", "Fpn.C2.3.conv3.weight", "Fpn.C2.3.conv3.bias", "Fpn.C3.0.conv1.0.weight", "Fpn.C3.0.conv1.0.bias", "Fpn.C3.0.conv2.0.weight", "Fpn.C3.0.conv2.0.bias", "Fpn.C3.0.conv3.weight", "Fpn.C3.0.conv3.bias", "Fpn.C3.0.downsample.weight", "Fpn.C3.0.downsample.bias", "Fpn.C3.1.conv1.0.weight", "Fpn.C3.1.conv1.0.bias", "Fpn.C3.1.conv2.0.weight", "Fpn.C3.1.conv2.0.bias", "Fpn.C3.1.conv3.weight", "Fpn.C3.1.conv3.bias", "Fpn.C3.2.conv1.0.weight", "Fpn.C3.2.conv1.0.bias", "Fpn.C3.2.conv2.0.weight", "Fpn.C3.2.conv2.0.bias", "Fpn.C3.2.conv3.weight", "Fpn.C3.2.conv3.bias", "Fpn.C3.3.conv1.0.weight", "Fpn.C3.3.conv1.0.bias", "Fpn.C3.3.conv2.0.weight", "Fpn.C3.3.conv2.0.bias", "Fpn.C3.3.conv3.weight", "Fpn.C3.3.conv3.bias", "Fpn.C4.0.conv1.0.weight", "Fpn.C4.0.conv1.0.bias", "Fpn.C4.0.conv2.0.weight", "Fpn.C4.0.conv2.0.bias", "Fpn.C4.0.conv3.weight", "Fpn.C4.0.conv3.bias", "Fpn.C4.0.downsample.weight", "Fpn.C4.0.downsample.bias", "Fpn.C4.1.conv1.0.weight", "Fpn.C4.1.conv1.0.bias", "Fpn.C4.1.conv2.0.weight", "Fpn.C4.1.conv2.0.bias", "Fpn.C4.1.conv3.weight", "Fpn.C4.1.conv3.bias", "Fpn.C4.2.conv1.0.weight", "Fpn.C4.2.conv1.0.bias", "Fpn.C4.2.conv2.0.weight", "Fpn.C4.2.conv2.0.bias", "Fpn.C4.2.conv3.weight", "Fpn.C4.2.conv3.bias", "Fpn.C4.3.conv1.0.weight", "Fpn.C4.3.conv1.0.bias", "Fpn.C4.3.conv2.0.weight", "Fpn.C4.3.conv2.0.bias", "Fpn.C4.3.conv3.weight", "Fpn.C4.3.conv3.bias", "Fpn.C4.4.conv1.0.weight", "Fpn.C4.4.conv1.0.bias", "Fpn.C4.4.conv2.0.weight", "Fpn.C4.4.conv2.0.bias", "Fpn.C4.4.conv3.weight", "Fpn.C4.4.conv3.bias", "Fpn.C4.5.conv1.0.weight", "Fpn.C4.5.conv1.0.bias", "Fpn.C4.5.conv2.0.weight", "Fpn.C4.5.conv2.0.bias", "Fpn.C4.5.conv3.weight", "Fpn.C4.5.conv3.bias", "Fpn.C5.0.conv1.0.weight", "Fpn.C5.0.conv1.0.bias", "Fpn.C5.0.conv2.0.weight", "Fpn.C5.0.conv2.0.bias", "Fpn.C5.0.conv3.weight", "Fpn.C5.0.conv3.bias", "Fpn.C5.0.downsample.weight", "Fpn.C5.0.downsample.bias", "Fpn.C5.1.conv1.0.weight", "Fpn.C5.1.conv1.0.bias", "Fpn.C5.1.conv2.0.weight", "Fpn.C5.1.conv2.0.bias", "Fpn.C5.1.conv3.weight", "Fpn.C5.1.conv3.bias", "Fpn.C5.2.conv1.0.weight", "Fpn.C5.2.conv1.0.bias", "Fpn.C5.2.conv2.0.weight", "Fpn.C5.2.conv2.0.bias", "Fpn.C5.2.conv3.weight", "Fpn.C5.2.conv3.bias", "Fpn.P5_conv1.weight", "Fpn.P5_conv1.bias", "Fpn.P4_conv1.weight", "Fpn.P4_conv1.bias", "Fpn.P3_conv1.weight", "Fpn.P3_conv1.bias", "Fpn.P2_conv1.weight", "Fpn.P2_conv1.bias", "Fpn.P1_conv1.weight", "Fpn.P1_conv1.bias", "Fpn.P1_conv2.weight", "Fpn.P1_conv2.bias", "Fpn.P2_conv2.weight", "Fpn.P2_conv2.bias", "Fpn.P3_conv2.weight", "Fpn.P3_conv2.bias", "Fpn.P4_conv2.weight", "Fpn.P4_conv2.bias", "Fpn.P5_conv2.weight", "Fpn.P5_conv2.bias".
        Unexpected key(s) in state_dict: "fpn.C1.0.weight", "fpn.C1.0.bias", "fpn.C2.1.conv1.0.weight", "fpn.C2.1.conv1.0.bias", "fpn.C2.1.conv2.0.weight", "fpn.C2.1.conv2.0.bias", "fpn.C2.1.conv3.weight", "fpn.C2.1.conv3.bias", "fpn.C2.1.downsample.0.weight", "fpn.C2.1.downsample.0.bias", "fpn.C2.2.conv1.0.weight", "fpn.C2.2.conv1.0.bias", "fpn.C2.2.conv2.0.weight", "fpn.C2.2.conv2.0.bias", "fpn.C2.2.conv3.weight", "fpn.C2.2.conv3.bias", "fpn.C2.3.conv1.0.weight", "fpn.C2.3.conv1.0.bias", "fpn.C2.3.conv2.0.weight", "fpn.C2.3.conv2.0.bias", "fpn.C2.3.conv3.weight", "fpn.C2.3.conv3.bias", "fpn.C3.0.conv1.0.weight", "fpn.C3.0.conv1.0.bias", "fpn.C3.0.conv2.0.weight", "fpn.C3.0.conv2.0.bias", "fpn.C3.0.conv3.weight", "fpn.C3.0.conv3.bias", "fpn.C3.0.downsample.0.weight", "fpn.C3.0.downsample.0.bias", "fpn.C3.1.conv1.0.weight", "fpn.C3.1.conv1.0.bias", "fpn.C3.1.conv2.0.weight", "fpn.C3.1.conv2.0.bias", "fpn.C3.1.conv3.weight", "fpn.C3.1.conv3.bias", "fpn.C3.2.conv1.0.weight", "fpn.C3.2.conv1.0.bias", "fpn.C3.2.conv2.0.weight", "fpn.C3.2.conv2.0.bias", "fpn.C3.2.conv3.weight", "fpn.C3.2.conv3.bias", "fpn.C3.3.conv1.0.weight", "fpn.C3.3.conv1.0.bias", "fpn.C3.3.conv2.0.weight", "fpn.C3.3.conv2.0.bias", "fpn.C3.3.conv3.weight", "fpn.C3.3.conv3.bias", "fpn.C4.0.conv1.0.weight", "fpn.C4.0.conv1.0.bias", "fpn.C4.0.conv2.0.weight", "fpn.C4.0.conv2.0.bias", "fpn.C4.0.conv3.weight", "fpn.C4.0.conv3.bias", "fpn.C4.0.downsample.0.weight", "fpn.C4.0.downsample.0.bias", "fpn.C4.1.conv1.0.weight", "fpn.C4.1.conv1.0.bias", "fpn.C4.1.conv2.0.weight", "fpn.C4.1.conv2.0.bias", "fpn.C4.1.conv3.weight", "fpn.C4.1.conv3.bias", "fpn.C4.2.conv1.0.weight", "fpn.C4.2.conv1.0.bias", "fpn.C4.2.conv2.0.weight", "fpn.C4.2.conv2.0.bias", "fpn.C4.2.conv3.weight", "fpn.C4.2.conv3.bias", "fpn.C4.3.conv1.0.weight", "fpn.C4.3.conv1.0.bias", "fpn.C4.3.conv2.0.weight", "fpn.C4.3.conv2.0.bias", "fpn.C4.3.conv3.weight", "fpn.C4.3.conv3.bias", "fpn.C4.4.conv1.0.weight", "fpn.C4.4.conv1.0.bias", "fpn.C4.4.conv2.0.weight", "fpn.C4.4.conv2.0.bias", "fpn.C4.4.conv3.weight", "fpn.C4.4.conv3.bias", "fpn.C4.5.conv1.0.weight", "fpn.C4.5.conv1.0.bias", "fpn.C4.5.conv2.0.weight", "fpn.C4.5.conv2.0.bias", "fpn.C4.5.conv3.weight", "fpn.C4.5.conv3.bias", "fpn.C5.0.conv1.0.weight", "fpn.C5.0.conv1.0.bias", "fpn.C5.0.conv2.0.weight", "fpn.C5.0.conv2.0.bias", "fpn.C5.0.conv3.weight", "fpn.C5.0.conv3.bias", "fpn.C5.0.downsample.0.weight", "fpn.C5.0.downsample.0.bias", "fpn.C5.1.conv1.0.weight", "fpn.C5.1.conv1.0.bias", "fpn.C5.1.conv2.0.weight", "fpn.C5.1.conv2.0.bias", "fpn.C5.1.conv3.weight", "fpn.C5.1.conv3.bias", "fpn.C5.2.conv1.0.weight", "fpn.C5.2.conv1.0.bias", "fpn.C5.2.conv2.0.weight", "fpn.C5.2.conv2.0.bias", "fpn.C5.2.conv3.weight", "fpn.C5.2.conv3.bias", "fpn.P5_conv1.weight", "fpn.P5_conv1.bias", "fpn.P4_conv1.weight", "fpn.P4_conv1.bias", "fpn.P3_conv1.weight", "fpn.P3_conv1.bias", "fpn.P2_conv1.weight", "fpn.P2_conv1.bias", "fpn.P1_conv1.weight", "fpn.P1_conv1.bias", "fpn.P1_conv2.weight", "fpn.P1_conv2.bias", "fpn.P2_conv2.weight", "fpn.P2_conv2.bias", "fpn.P3_conv2.weight", "fpn.P3_conv2.bias", "fpn.P4_conv2.weight", "fpn.P4_conv2.bias", "fpn.P5_conv2.weight", "fpn.P5_conv2.bias".
```

For this capslock incompatibility I edit `self.Fpn `at retinanet.py to `self.fpn`, and it work for conv layer, however the next one occur for downsample weight and bias

```
Traceback (most recent call last):
  File "exec.py", line 167, in <module>
    train(logger)
  File "exec.py", line 46, in train
      starting_epoch = utils.load_checkpoint(cf.resume_to_checkpoint, net, optimizer)
  File "/home/ivan/retcustom3d/utils/exp_utils.py", line 186, in load_checkpoint
    net.load_state_dict(checkpoint['state_dict'])
  File "/home/ivan/.virtualenvs/virtual-py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for net:
        Missing key(s) in state_dict: "fpn.C2.1.downsample.bias", "fpn.C2.1.downsample.weight", "fpn.C3.0.downsample.bias", "fpn.C3.0.downsample.weight", "fpn.C4.0.downsample.bias", "fpn.C4.0.downsample.weight", "fpn.C5.0.downsample.bias", "fpn.C5.0.downsample.weight".
        Unexpected key(s) in state_dict: "fpn.C2.1.downsample.0.weight", "fpn.C2.1.downsample.0.bias", "fpn.C3.0.downsample.0.weight", "fpn.C3.0.downsample.0.bias", "fpn.C4.0.downsample.0.weight", "fpn.C4.0.downsample.0.bias", "fpn.C5.0.downsample.0.weight", "fpn.C5.0.downsample.0.bias".
```

Solution 
1) adding variable self.downsample -->  self.downsample.0  (failed)
2) set torch.load_state_dict (strict = False) --> able to run from epoch 100, however index out of range for train or train_test mode

```
starting training epoch 100

tr. batch 1/50 (ep. 100) fw 7.221s / bw 2.101s / total 9.322s || loss: 3.70, class: 3.50, bbox: 0.20
tr. batch 2/50 (ep. 100) fw 6.843s / bw 2.012s / total 8.855s || loss: 1.11, class: 0.93, bbox: 0.18
tr. batch 3/50 (ep. 100) fw 5.348s / bw 2.008s / total 7.356s || loss: 0.90, class: 0.71, bbox: 0.19
tr. batch 4/50 (ep. 100) fw 5.678s / bw 2.025s / total 7.703s || loss: 1.55, class: 1.27, bbox: 0.28
tr. batch 5/50 (ep. 100) fw 6.815s / bw 2.021s / total 8.837s || loss: 0.95, class: 0.77, bbox: 0.18
tr. batch 6/50 (ep. 100) fw 7.942s / bw 2.021s / total 9.963s || loss: 1.37, class: 1.16, bbox: 0.21
tr. batch 7/50 (ep. 100) fw 8.728s / bw 2.048s / total 10.776s || loss: 1.41, class: 1.07, bbox: 0.35
tr. batch 8/50 (ep. 100) fw 7.288s / bw 2.026s / total 9.314s || loss: 1.57, class: 1.30, bbox: 0.27
tr. batch 9/50 (ep. 100) fw 8.727s / bw 2.015s / total 10.742s || loss: 1.15, class: 0.97, bbox: 0.18
tr. batch 10/50 (ep. 100) fw 8.047s / bw 2.003s / total 10.050s || loss: 0.79, class: 0.70, bbox: 0.09
tr. batch 11/50 (ep. 100) fw 5.477s / bw 2.022s / total 7.499s || loss: 0.96, class: 0.84, bbox: 0.12
tr. batch 12/50 (ep. 100) fw 7.219s / bw 2.012s / total 9.231s || loss: 1.04, class: 0.94, bbox: 0.09
tr. batch 13/50 (ep. 100) fw 7.120s / bw 2.029s / total 9.149s || loss: 0.95, class: 0.77, bbox: 0.18
tr. batch 14/50 (ep. 100) fw 6.659s / bw 2.022s / total 8.681s || loss: 0.82, class: 0.72, bbox: 0.10
tr. batch 15/50 (ep. 100) fw 6.781s / bw 2.006s / total 8.787s || loss: 0.88, class: 0.74, bbox: 0.13
tr. batch 16/50 (ep. 100) fw 7.215s / bw 2.011s / total 9.226s || loss: 1.09, class: 0.94, bbox: 0.16
tr. batch 17/50 (ep. 100) fw 4.831s / bw 1.996s / total 6.828s || loss: 0.77, class: 0.67, bbox: 0.10
tr. batch 18/50 (ep. 100) fw 7.607s / bw 2.024s / total 9.631s || loss: 0.99, class: 0.79, bbox: 0.20
tr. batch 19/50 (ep. 100) fw 7.291s / bw 2.018s / total 9.310s || loss: 1.11, class: 0.87, bbox: 0.23
tr. batch 20/50 (ep. 100) fw 7.864s / bw 2.029s / total 9.893s || loss: 0.87, class: 0.68, bbox: 0.19
tr. batch 21/50 (ep. 100) fw 6.009s / bw 2.059s / total 8.068s || loss: 0.89, class: 0.74, bbox: 0.14
tr. batch 22/50 (ep. 100) fw 6.142s / bw 2.020s / total 8.162s || loss: 1.05, class: 0.88, bbox: 0.17
tr. batch 23/50 (ep. 100) fw 5.101s / bw 2.002s / total 7.103s || loss: 0.79, class: 0.68, bbox: 0.11
tr. batch 24/50 (ep. 100) fw 7.096s / bw 2.020s / total 9.116s || loss: 0.99, class: 0.80, bbox: 0.18
tr. batch 25/50 (ep. 100) fw 7.429s / bw 1.994s / total 9.423s || loss: 0.86, class: 0.67, bbox: 0.19
tr. batch 26/50 (ep. 100) fw 5.912s / bw 2.019s / total 7.932s || loss: 0.94, class: 0.79, bbox: 0.15
tr. batch 27/50 (ep. 100) fw 7.303s / bw 2.010s / total 9.313s || loss: 1.06, class: 0.78, bbox: 0.28
tr. batch 28/50 (ep. 100) fw 6.317s / bw 2.002s / total 8.320s || loss: 0.64, class: 0.59, bbox: 0.05
tr. batch 29/50 (ep. 100) fw 8.409s / bw 2.010s / total 10.419s || loss: 0.82, class: 0.68, bbox: 0.14
tr. batch 30/50 (ep. 100) fw 6.803s / bw 2.004s / total 8.807s || loss: 0.77, class: 0.68, bbox: 0.09
tr. batch 31/50 (ep. 100) fw 7.824s / bw 2.009s / total 9.833s || loss: 0.77, class: 0.63, bbox: 0.14
tr. batch 32/50 (ep. 100) fw 8.600s / bw 2.002s / total 10.602s || loss: 0.86, class: 0.74, bbox: 0.12
tr. batch 33/50 (ep. 100) fw 10.036s / bw 2.046s / total 12.082s || loss: 0.99, class: 0.79, bbox: 0.19
tr. batch 34/50 (ep. 100) fw 8.687s / bw 2.028s / total 10.715s || loss: 0.91, class: 0.75, bbox: 0.16
tr. batch 35/50 (ep. 100) fw 9.219s / bw 2.025s / total 11.244s || loss: 0.90, class: 0.70, bbox: 0.20
tr. batch 36/50 (ep. 100) fw 8.416s / bw 2.115s / total 10.532s || loss: 1.10, class: 0.87, bbox: 0.23
tr. batch 37/50 (ep. 100) fw 5.734s / bw 2.007s / total 7.741s || loss: 0.70, class: 0.58, bbox: 0.13
tr. batch 38/50 (ep. 100) fw 7.441s / bw 2.006s / total 9.447s || loss: 0.57, class: 0.51, bbox: 0.06
tr. batch 39/50 (ep. 100) fw 7.173s / bw 2.025s / total 9.198s || loss: 1.00, class: 0.83, bbox: 0.16
tr. batch 40/50 (ep. 100) fw 6.762s / bw 2.017s / total 8.778s || loss: 0.90, class: 0.72, bbox: 0.19
tr. batch 41/50 (ep. 100) fw 6.915s / bw 2.014s / total 8.929s || loss: 0.93, class: 0.77, bbox: 0.17
tr. batch 42/50 (ep. 100) fw 6.596s / bw 2.008s / total 8.604s || loss: 0.99, class: 0.85, bbox: 0.14
tr. batch 43/50 (ep. 100) fw 8.112s / bw 2.040s / total 10.152s || loss: 0.50, class: 0.44, bbox: 0.05
tr. batch 44/50 (ep. 100) fw 6.126s / bw 2.022s / total 8.148s || loss: 1.11, class: 0.86, bbox: 0.25
tr. batch 45/50 (ep. 100) fw 5.511s / bw 2.031s / total 7.542s || loss: 0.96, class: 0.75, bbox: 0.21
tr. batch 46/50 (ep. 100) fw 7.721s / bw 2.009s / total 9.730s || loss: 0.87, class: 0.71, bbox: 0.16
tr. batch 47/50 (ep. 100) fw 5.878s / bw 2.038s / total 7.916s || loss: 0.92, class: 0.74, bbox: 0.19
tr. batch 48/50 (ep. 100) fw 7.050s / bw 2.030s / total 9.080s || loss: 0.96, class: 0.79, bbox: 0.16
tr. batch 49/50 (ep. 100) fw 8.159s / bw 2.072s / total 10.231s || loss: 1.03, class: 0.87, bbox: 0.16
tr. batch 50/50 (ep. 100) fw 9.161s / bw 2.031s / total 11.191s || loss: 0.80, class: 0.70, bbox: 0.10
evaluating in mode train
evaluating with match_iou: 0.1
starting validation in mode val_sampling.
evaluating in mode val_sampling
evaluating with match_iou: 0.1
non none scores: [0.00000000e+00 2.64303791e-05]
Traceback (most recent call last):
  File "exec.py", line 167, in <module>
    train(logger)
  File "exec.py", line 102, in train
    TrainingPlot.update_and_save(monitor_metrics, epoch)
  File "/home/ivan/retcustom3d/plotting.py", line 189, in update_and_save
    self.do_validation)
  File "/home/ivan/retcustom3d/plotting.py", line 195, in detection_monitoring_plot
    monitor_values_keys = metrics['train']['monitor_values'][1][0].keys()
IndexError: list index out of range
```

Do you have some trick to supress the error Sir?
Thank you in advance Sir.

**Comment by ivanwilliammd** [comment]
btw I already consult with my mentor about the problem, it seems it caused by incompatible pytorch version.
May I ask what version of pytorch you run, and what is the solution for this problem?
Thank you Sir.
