### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8

### ISSUE THREAD

**Issue by lly2111101** [MIC-DKFZ/medicaldetectiontoolkit#56]

**Comment by lly2111101** [comment]
Hi, when I run test mode using lidc_exp with 93 patients in LIDC dataset, it reports the follow error:

Logging to snapshots/fold_0/exec.log
starting testing model of fold 0 in exp snapshots
feature map shapes: [[32 32 64]
 [16 16 32]
 [ 8  8 16]
 [ 4  4  8]]
anchor scales: {'xy': [[8], [16], [32], [64]], 'z': [[2], [4], [8], [16]]}
level 0: built anchors (196608, 6) / expected anchors 196608 ||| total build (196608, 6) / total expected 224640
level 1: built anchors (24576, 6) / expected anchors 24576 ||| total build (221184, 6) / total expected 224640
level 2: built anchors (3072, 6) / expected anchors 3072 ||| total build (224256, 6) / total expected 224640
level 3: built anchors (384, 6) / expected anchors 384 ||| total build (224640, 6) / total expected 224640
using default pytorch weight init
subset: selected 19 instances from df
data set loaded with: 19 test patients
tmp ensembling over rank_ix:0 epoch:snapshots/fold_0/44_best_checkpoint/params.pth
evaluating patient 0044a for fold 0
forwarding (patched) patient with shape: (150,)
Traceback (most recent call last):
  File "exec.py", line 187, in <module>
    test(logger)
  File "exec.py", line 123, in test
    test_results_list = test_predictor.predict_test_set(batch_gen, return_results=True)
  File "/data/medicaldetectiontoolkit/predictor.py", line 160, in predict_test_set
    results_dict = self.predict_patient(batch)
  File "/data/medicaldetectiontoolkit/predictor.py", line 102, in predict_patient
    results_dict = self.data_aug_forward(batch)
  File "/data/medicaldetectiontoolkit/predictor.py", line 293, in data_aug_forward
    results_list = [self.spatial_tiling_forward(batch, patch_crops)]
  File "/data/medicaldetectiontoolkit/predictor.py", line 388, in spatial_tiling_forward
    patches_dict = self.batch_tiling_forward(batch)
  File "/data/medicaldetectiontoolkit/predictor.py", line 494, in batch_tiling_forward
    chunk_dicts += [self.net.test_forward(b, return_masks=self.cf.return_masks_in_test)]
  File "/data/medicaldetectiontoolkit/models/tmp_model.py", line 981, in test_forward
    img = torch.from_numpy(img).float().cuda()
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.

Does anyone have any ideas to solve the problem?

**Comment by lly2111101** [comment]
The above problem is solved, however, there is another problem which is shown bellow:
anchor scales: {'xy': [[8], [16], [32], [64]], 'z': [[2], [4], [8], [16]]}
level 0: built anchors (196608, 6) / expected anchors 196608 ||| total build (196608, 6) / total expected 224640
level 1: built anchors (24576, 6) / expected anchors 24576 ||| total build (221184, 6) / total expected 224640
level 2: built anchors (3072, 6) / expected anchors 3072 ||| total build (224256, 6) / total expected 224640
level 3: built anchors (384, 6) / expected anchors 384 ||| total build (224640, 6) / total expected 224640
using default pytorch weight init
subset: selected 19 instances from df
data set loaded with: 19 test patients
tmp ensembling over rank_ix:0 epoch:snapshots/fold_0/38_best_checkpoint/params.pth
evaluating patient 0044a for fold 0
forwarding (patched) patient with shape: (150,)
Traceback (most recent call last):
  File "exec.py", line 189, in <module>
    test(logger)
  File "exec.py", line 123, in test
    test_results_list = test_predictor.predict_test_set(batch_gen, return_results=True)
  File "/medicaldetectiontoolkit/predictor.py", line 160, in predict_test_set
    results_dict = self.predict_patient(batch)
  File "/medicaldetectiontoolkit/predictor.py", line 102, in predict_patient
    results_dict = self.data_aug_forward(batch)
  File "/medicaldetectiontoolkit/predictor.py", line 293, in data_aug_forward
    results_list = [self.spatial_tiling_forward(batch, patch_crops)]
  File "/medicaldetectiontoolkit/predictor.py", line 388, in spatial_tiling_forward
    patches_dict = self.batch_tiling_forward(batch)
  File "/medicaldetectiontoolkit/predictor.py", line 494, in batch_tiling_forward
    chunk_dicts += [self.net.test_forward(b, return_masks=self.cf.return_masks_in_test)]
  File "/medicaldetectiontoolkit/models/tmp_model.py", line 984, in test_forward
    _, _, _, detections, detection_masks = self.forward(img)
  File "/medicaldetectiontoolkit/models/tmp_model.py", line 1018, in forward
    batch_rpn_rois, batch_proposal_boxes = proposal_layer(rpn_pred_probs, rpn_pred_deltas, proposal_count, self.anchors, self.cf)
  File "/medicaldetectiontoolkit/models/tmp_model.py", line 333, in proposal_layer
    anchors = anchors[order, :]
RuntimeError: index 516019 is out of bounds for dimension 0 with size 224640

**Comment by smallrookie** [comment]
`TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.`

Hi, Could you tell me how to solve this problem? Thanks!

**Comment by Luchixiang** [comment]
@lly2111101 hey have u ever solved it?
