### ISSUE TITLE
No epoch_ranking.npy

### ISSUE THREAD

**Issue by WENJIANHUANG** [MIC-DKFZ/medicaldetectiontoolkit#65]
**There is an error when running test(logger) in exec.py**

        for fold in folds:
            cf.fold_dir = os.path.join(cf.exp_dir, 'fold_{}'.format(fold))
            cf.fold = fold
            cf.resume_to_checkpoint = resume_to_checkpoint
            if not os.path.exists(cf.fold_dir):
                os.mkdir(cf.fold_dir)
            logger = utils.get_logger(cf.fold_dir)
            train(logger) 
            cf.resume_to_checkpoint = None
            if args.mode == 'train_test':
                test(logger)

**I got the following error** 

Traceback (most recent call last):
  File "/home/XXX/YYY/medicaldetectiontoolkit/predictor.py", line 71, in __init__
    self.epoch_ranking = np.load(os.path.join(self.cf.fold_dir, 'epoch_ranking.npy'))[:cf.test_n_epochs]
  File "/home/XXX/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/XXX/YYY/medicaldetectiontoolkit/fold_0/epoch_ranking.npy'

**the model do not automatically save epoch_ranking.npy file during the trainning process?**

**Comment by WENJIANHUANG** [comment]
The problem solved after  I set the do_validation to True.
