### ISSUE TITLE
No dataset loaded in val

### ISSUE THREAD

**Issue by paul-bd** [MIC-DKFZ/medicaldetectiontoolkit#8]
Hi, I am trying the toynet expermiment which is running for one epoch, but no patients seems to be loaded in the validation dataset : 
`data set loaded with: 50 train / 0 val patients`

 which leads to this error : 

`WARNING:matplotlib.legend:No handles with labels found to put in legend.
/home/paulbd/anaconda3/envs/MDK/lib/python3.6/site-packages/pandas/core/ops.py:1167: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)
Traceback (most recent call last):
  File "exec.py", line 167, in <module>
    train(logger)
  File "exec.py", line 98, in train
    _, monitor_metrics['val'] = val_evaluator.evaluate_predictions(val_results_list, monitor_metrics['val'])
  File "/home/paulbd/medicaldetectiontoolkit/evaluator.py", line 191, in evaluate_predictions
    return self.return_metrics(monitor_metrics)
  File "/home/paulbd/medicaldetectiontoolkit/evaluator.py", line 218, in return_metrics
    spec_df = cl_df[cl_df.det_type != 'patient_tn']
  File "/home/paulbd/anaconda3/envs/MDK/lib/python3.6/site-packages/pandas/core/ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "/home/paulbd/anaconda3/envs/MDK/lib/python3.6/site-packages/pandas/core/ops.py", line 1169, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison`

And I can't figure out which parameters to change in the config (self.do_validation=True,...) , as I have read that it was automatically splitted into 20% of the training cohort and therefore don't understand why it doesn't work. 

Best regards and thanks for your help,

Paul

**Comment by paul-bd** [comment]
Found !
 - in data_loader : def get_train_generator val_pids can be modified
